---
title: "Help improving the LA Jails scraper"
author: "UCLA COVID Behind Bars Data Team"
date: "1/06/2020"
output: 
  html_document
---

Currently one of the most problematic scrapers is the `la_jails` scraper. Data for the scraper is pulled from a pdf hosted on the [Los Angeles Sheriff's department](https://lasd.org/covid19updates/) website and from this file a series of OCR functions are run on the scraper in order to extract the data that is most relevant to our team. The problem is the file itself changes size, borders, and quality making it hard to have a single code base which is able to extract the data consistently. The current iteration of our scraper may be found [here](https://github.com/uclalawcovid19behindbars/covid19_behind_bars_scrapers/blob/master/production/scrapers/lasd.R). In order to improve this process we are seeking the help of volunteers to improve the code for extraction of covid data from the LASD website. By forking our repo and making changes to the `la_jails` scraper code we hope that you can re-extract our [historical record of raw files](http://104.131.72.50:3838/scraper_data/raw_files/) with a new and improved version of the LASD scraper. The process would look something like this.

1. Edit the code
2. Initialize the scraper `lasd <- lasd_scraper$new(log=FALSE)`
3. Pick a historical scraper date from the list provided by `list_remote_data("raw_files", "lasd", TRUE)`
4. Pull the raw data from that date
5. Run the rest of the extraction functions
6. If you run without any warnings then your edits were robust enough to extract data for that date! and you can start from step 2 and select a new date from step 3. If you did get errors try going back to editing, step 1, and rerunning the code without changing the date.

## More detailed example

```{r eval=FALSE}
# assuming you are in the covid19_behind_bars_scrapers repo
# and have edited the code ie step 1
library(tidyverse)
library(behindbarstools)
source("./production/scrapers/lasd.R")

# step 2 initialize the scraper
lasd <- lasd_scraper$new(log=FALSE)

# step 3 select a date from this list and set the scraper to that date
lasd_dates <- list_remote_data("raw_files", "lasd", TRUE)
lasd$reset_date("2020-11-19") # any date from the vector above will work

# step 4 
lasd$pull_raw()

# step 5
lasd$restruct_data()
lasd$extract_from_raw()
lasd$validate_extract()

# Were there no warnings? Noice! save and start from step 2 but pick a different date
lasd$save_extract()

# Some warnings? You will need to go back to edit your code and try again.

```

By using the `renv` package you should be set up with an R environment that is ready to use our code with all the necessary packages we require.